# Trigger pipeline when code is pushed to master
# trigger:
# - main

trigger:
   branches:
     include:
       - master

pr:
  branches:
    include:
      - master

# Use self-hosted agent pool
pool:
  name: Default

# Define stages
stages:
  - stage: 'UT'
    displayName: 'Unit Test Stage'
    jobs:
      - job: 'unitTest'
        displayName: 'Running Unit Tests'
        steps:
          - script: echo 'Running a demo app unit test'
            # displayName: 'Echo Message'

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
            displayName: 'Set Python Version'
            
  - stage: 'Build'
    displayName: 'build the script'
    jobs:
      - job: 'buildscript'
        displayName: 'building a script'
        steps:
          -  script: echo 'Running a demo app unit test'
            # displayName: 'Echo Message'

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
            displayName: 'Set Python Version'

  - stage: 'Runscript'
    displayName: "Running a script"
    jobs:
      - job: 'runpyscript'
        steps: 
        - script: |
            py main.py
            echo " successfully runned the script"
           

