# Trigger pipeline when code is pushed to master
trigger:
- master

# Use self-hosted agent pool
pool:
  name: Default

# Define stages
stages:
  - stage: 'UT'
    displayName: 'Unit Test Stage'
    jobs:
      - job: 'unitTest'
        displayName: 'Running Unit Tests'
        steps:
          - script: echo 'Running a demo app unit test'
            displayName: 'Echo Message'

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
            displayName: 'Set Python Version'
