# Stage 

trigger:
- master
#
pool:
  name: Default

# pool:
#   vmImage: ubuntu-latest

stages:
  - stage: 'UT'
    displayName: 'UT stage'
    jobs:
      - job: 'unitTest'
        displayName: 'Running unit tests'
        steps:
          - script: echo 'RUnning a demo app unit test'
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
              