# Stage 

trigger:
- main

pool:
  name: Default

# pool:
#   vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    python --version
  displayName: 'Run a multi-line script'
